# NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2

1.56 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

70.8 ms ± 1.76 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## The NumPy ndarray: A Multidimensional Array Object

In [5]:
import numpy as np

data = np.array([[1.5, -.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [6]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [7]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [8]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Creating ndarrays

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
print(arr2.ndim) # 2
print(arr2.shape) # (2, 4)

2
(2, 4)


In [12]:
print(arr1.dtype) # float64
print(arr2.dtype) # int32

float64
int32


In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((1, 2, 3))

array([[[ 3. , -0.2,  6. ],
        [ 0. , -6. , 13. ]]])

In [18]:
np.arange(15)
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

### Data Types for ndarrays

In [20]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype) # float64
print(arr2.dtype) # int32

float64
int32


In [21]:
arr = np.array([1, 2, 3, 4, 5])
print(arr) # [1 2 3 4 5]
print(arr.dtype) # int32
float_arr = arr.astype(np.float64)
print(float_arr) # [1. 2. 3. 4. 5.]
print(float_arr.dtype) # float64

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float64


In [22]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)
# array([ 3, -1, -2,  0, 12, 10])

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [23]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)
# array([ 1.25, -9.6 , 42.  ])

array([ 1.25, -9.6 , 42.  ])

In [24]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)
# array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
zeros_unit32 = np.zeros(8, dtype='u4')
zeros_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Arithmetic with NumPy Arrays


In [29]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [36]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [89]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
arr[5]
# 5

5

In [91]:
arr[5: 8]
# array([5, 6, 7])

array([5, 6, 7])

In [92]:
arr[5: 8] = 12
arr
# array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [93]:
arr_slice = arr[5: 8]
arr_slice
# array([12, 12, 12])
arr_slice[1] = 123
arr
# array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

arr_slice[:] = 64
arr
# array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

In [77]:
a = list(range(10))
print(a)
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
b = a[2: 5]
# [2, 3, 4]
print(b)
b[1] = 1234
print(b)
# [2, 1234, 4]
print(a)
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4]
[2, 1234, 4]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [94]:
arr_slice

array([ 12, 123,  12])

In [95]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [49]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]
# array([7, 8, 9])

array([7, 8, 9])

In [50]:
arr2d[0][2]

3

In [51]:
arr2d[0, 2]

3

In [103]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]

old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d[0] = old_values

arr3d[1, 0]

x = arr3d[1]
x[0]
# array([7, 8, 9])

array([7, 8, 9])

#### Indexing with slices

In [104]:
arr
# array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])
arr[1: 6]
# array([ 1,  2,  3,  4, 64])

array([ 1,  2,  3,  4, 64])

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[: 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [111]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice.shape

arr2d[:2, 2]
arr2d[:, :1]

arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 0, 0]])

In [141]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, 4], [3, 4]])
data
names == "Bob"
data[names == "Bob"]
data[names == "Bob", 1:]
data[names == "Bob", 1]

names != "Bob"
~(names == "Bob")
data[~(names == "Bob")]
cond = names == "Bob"
data[~cond]

mask = (names == "Bob") | (names == "Will")
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [134]:
names != "Bob"
~(names == "Bob")
data[~(names == "Bob")]
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,   4],
       [  3,   4]])

In [140]:
mask = (names == "Bob") | (names == "Will")
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [146]:
data[data < 0] = 0
data

data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 4],
       [3, 4]])

### Fancy Indexing

In [189]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

arr[[4, 3, 0, 6]]

arr[[-3, -5, -7]]

arr = np.arange(32).reshape((8, 4))
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [190]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [197]:
a = arr[[1, 5, 7, 2], [0, 3, 1, 2]]
a[0] = 10000
print(a)
print(arr)

[10000    23    29    10]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


### Transposing Arrays and Swapping Axes

In [199]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [200]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [202]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [203]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [206]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [207]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [208]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [218]:
arr = np.arange(16).reshape((2, 2, 4))
arr.transpose((2, 0, 1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])