# NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr2 = my_arr * 2

1.97 ms ± 298 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

106 ms ± 14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## The NumPy ndarray: A Multidimensional Array Object

In [6]:
import numpy as np

data = np.array([[1.5, -.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [7]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [8]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [9]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


### Creating ndarrays

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
print(arr2.ndim) # 2
print(arr2.shape) # (2, 4)

2
(2, 4)


In [13]:
print(arr1.dtype) # float64
print(arr2.dtype) # int32

float64
int32


In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.empty((1, 2, 3))

array([[[ 3. , -0.2,  6. ],
        [ 0. , -6. , 13. ]]])

In [19]:
np.arange(15)
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

### Data Types for ndarrays

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype) # float64
print(arr2.dtype) # int32

float64
int32


In [22]:
arr = np.array([1, 2, 3, 4, 5])
print(arr) # [1 2 3 4 5]
print(arr.dtype) # int32
float_arr = arr.astype(np.float64)
print(float_arr) # [1. 2. 3. 4. 5.]
print(float_arr.dtype) # float64

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float64


In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)
# array([ 3, -1, -2,  0, 12, 10])

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [34]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)
# array([ 1.25, -9.6 , 42.  ])

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)
# array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
zeros_unit32 = np.zeros(8, dtype='u4')
zeros_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)